/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 19, 2016 at 11:57:11 AM Mountain Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libactivator.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libactivator.dylib/libactivator.dylib-Structs.h>
@class NSDictionary, NSMutableDictionary, NSArray, NSString;

@interface LAActivator : NSObject {

	NSDictionary* _cachedPreferences;
	NSMutableDictionary* _cachedListenerTitles;
	NSMutableDictionary* _cachedListenerDescriptions;
	NSMutableDictionary* _cachedListenerGroups;
	int _preference_notify_token;
	unsigned long long _preferences_change_count;
	NSArray* _configurableListenerNames;

}

@property (nonatomic,readonly) int version; 
@property (getter=isRunningInsideSpringBoard,nonatomic,readonly) BOOL runningInsideSpringBoard; 
@property (getter=isDangerousToSendEvents,nonatomic,readonly) BOOL dangerousToSendEvents; 
@property (nonatomic,readonly) NSArray * availableEventNames; 
@property (nonatomic,readonly) NSArray * availableListenerNames; 
@property (nonatomic,readonly) NSArray * availableEventModes; 
@property (nonatomic,readonly) NSString * currentEventMode; 
@property (nonatomic,readonly) NSString * currentEventModeUnderneathLockScreen; 
@property (nonatomic,readonly) BOOL supportsUnlockingDeviceToSendEvents; 
@property (nonatomic,readonly) NSString * displayIdentifierForCurrentApplication; 
@property (nonatomic,readonly) NSArray * availableProfileNames; 
@property (nonatomic,copy) NSString * currentProfileName; 
@property (nonatomic,readonly) int authorizationStatus; 
@property (getter=isAlive,nonatomic,readonly) BOOL alive; 
@property (nonatomic,readonly) SCD_Struct_LA1 _objectStatistics; 
+(id)sharedInstance;
+(id)allocWithZone:(NSZone*)arg1 ;
+(void)initialize;
-(id)localizedGroupForListenerName:(id)arg1 ;
-(id)localizedTitleForListenerName:(id)arg1 ;
-(id)localizedGroupForEventName:(id)arg1 ;
-(id)localizedDescriptionForListenerName:(id)arg1 ;
-(id)localizedDescriptionForEventName:(id)arg1 ;
-(id)localizedDescriptionForEventMode:(id)arg1 ;
-(id)localizedTitleForEventName:(id)arg1 ;
-(id)localizedStringForKey:(id)arg1 value:(id)arg2 ;
-(id)localizedTitleForEventMode:(id)arg1 ;
-(id)localizedTitleForListenerNames:(id)arg1 ;
-(void)registerListener:(id)arg1 forName:(id)arg2 ;
-(void)removeListenerAssignment:(id)arg1 fromEvent:(id)arg2 ;
-(id)compatibleEventModesForListenerWithName:(id)arg1 ;
-(BOOL)listenerWithNameRequiresAssignment:(id)arg1 ;
-(id)eventsAssignedToListenerWithName:(id)arg1 ;
-(void)_deleteExportedPreferences;
-(id)_configurationForEvent:(id)arg1 ;
-(id)configurationViewControllerForListenerWithName:(id)arg1 ;
-(BOOL)_canOpenURL:(id)arg1 ;
-(id)listenerForEvent:(id)arg1 ;
-(NSString *)currentEventMode;
-(void)_dropMetadataCache;
-(void)requestAuthorization;
-(id)_configurationForListener:(id)arg1 ;
-(BOOL)isDangerousToSendEvents;
-(id)configurationViewControllerForEventWithName:(id)arg1 ;
-(BOOL)hasListenerWithName:(id)arg1 ;
-(NSArray *)availableEventModes;
-(BOOL)isAlive;
-(void)requestRemovalForListenerWithName:(id)arg1 ;
-(void)sendEventToListener:(id)arg1 ;
-(BOOL)eventWithNameSupportsUnlockingDeviceToSend:(id)arg1 ;
-(BOOL)listenerWithNameSupportsRemoval:(id)arg1 ;
-(id)_configurableListenerNames;
-(id)assignmentWarningForEventWithName:(id)arg1 ;
-(void)sendEvent:(id)arg1 toListenerWithName:(id)arg2 ;
-(void)sendEvent:(id)arg1 toListenersWithNames:(id)arg2 ;
-(id)_getObjectForPreference:(id)arg1 ;
-(BOOL)listenerWithNameSupportsConfiguration:(id)arg1 ;
-(id)_localizedTitleForListenerName:(id)arg1 ;
-(void)sendDeactivateEventToListeners:(id)arg1 ;
-(void)registerEventDataSource:(id)arg1 forEventName:(id)arg2 ;
-(BOOL)applicationWithDisplayIdentifierIsBlacklisted:(id)arg1 ;
-(void)unregisterEventDataSourceWithEventName:(id)arg1 ;
-(void)unassignEvent:(id)arg1 ;
-(void)sendAbortToListener:(id)arg1 ;
-(void)_updateEvent:(id)arg1 withConfiguration:(id)arg2 ;
-(NSArray *)availableListenerNames;
-(BOOL)_debuggingLocalizationBundle;
-(BOOL)listenerWithName:(id)arg1 isCompatibleWithEventName:(id)arg2 ;
-(id)assignedListenerNamesForEvent:(id)arg1 ;
-(void)sendAbortEvent:(id)arg1 toListenerWithName:(id)arg2 ;
-(void)assignEvent:(id)arg1 toListenersWithNames:(id)arg2 ;
-(id)_directImageForListenerName:(id)arg1 usingTemplate:(id)arg2 ;
-(BOOL)eventWithNameSupportsConfiguration:(id)arg1 ;
-(id)uncachedSmallIconForListenerName:(id)arg1 ;
-(void)_updateListener:(id)arg1 withConfiguration:(id)arg2 ;
-(Class)configurationViewControllerClassForListenerWithName:(id)arg1 ;
-(BOOL)eventWithNameSupportsRemoval:(id)arg1 ;
-(NSString *)currentEventModeUnderneathLockScreen;
-(void)removeEventWithName:(id)arg1 ;
-(NSString *)displayIdentifierForCurrentApplication;
-(void)sendPreviewEventToListenerWithName:(id)arg1 ;
-(id)exclusiveAssignmentGroupsForListenerName:(id)arg1 ;
-(BOOL)supportsUnlockingDeviceToSendEvents;
-(void)addListenerAssignment:(id)arg1 toEvent:(id)arg2 ;
-(NSArray *)availableProfileNames;
-(void)assignEvent:(id)arg1 toListenerWithName:(id)arg2 ;
-(id)assignedListenerNameForEvent:(id)arg1 ;
-(BOOL)eventWithName:(id)arg1 isCompatibleWithMode:(id)arg2 ;
-(NSArray *)availableEventNames;
-(BOOL)listenerWithName:(id)arg1 isCompatibleWithMode:(id)arg2 ;
-(id)cachedSmallIconForListenerName:(id)arg1 ;
-(id)listenerForName:(id)arg1 ;
-(void)setCurrentProfileName:(NSString *)arg1 ;
-(NSString *)currentProfileName;
-(void)_resetPreferences;
-(void)_cacheAllListenerMetadata;
-(id)_cachedAndSortedListeners;
-(void)unregisterListenerWithName:(id)arg1 ;
-(id)infoDictionaryValueOfKey:(id)arg1 forListenerWithName:(id)arg2 ;
-(id)_incompatibleListenersForEventWithName:(id)arg1 andModes:(id)arg2 ;
-(BOOL)hasSeenListenerWithName:(id)arg1 ;
-(id)_allPreferences;
-(BOOL)_canImportPreferences;
-(BOOL)eventWithNameIsHidden:(id)arg1 ;
-(id)iconForListenerName:(id)arg1 ;
-(void)_makeRoomInIconCacheForListenerName:(id)arg1 ;
-(BOOL)eventWithNameRequiresAssignment:(id)arg1 ;
-(void)_exportPreferences;
-(id)compatibleModesForEventWithName:(id)arg1 ;
-(void)_importPreferences;
-(void)_backgroundCacheListenerData;
-(id)imageForListenerName:(id)arg1 usingTemplate:(id)arg2 ;
-(Class)configurationViewControllerClassForEventWithName:(id)arg1 ;
-(void)sendAbortEvent:(id)arg1 toListenersWithNames:(id)arg2 ;
-(BOOL)listenerWithNameNeedsPoweredDisplay:(id)arg1 ;
-(BOOL)isRunningInsideSpringBoard;
-(id)configurationViewControllerClassNameForEventWithName:(id)arg1 bundle:(id*)arg2 ;
-(id)smallIconForListenerName:(id)arg1 ;
-(void)setApplicationWithDisplayIdentifier:(id)arg1 isBlacklisted:(BOOL)arg2 ;
-(BOOL)listenerNamesAreMutuallyCompatible:(id)arg1 ;
-(id)configurationViewControllerClassNameForListenerWithName:(id)arg1 bundle:(id*)arg2 ;
-(SCD_Struct_LA1)_objectStatistics;
-(BOOL)_setObject:(id)arg1 forPreference:(id)arg2 ;
-(id)description;
-(int)version;
-(int)authorizationStatus;
-(BOOL)hasEventWithName:(id)arg1 ;
@end

