/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 19, 2016 at 11:57:11 AM Mountain Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libactivator.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libactivator.dylib/libactivator.dylib-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>

@class NSString, NSDictionary;

@interface LAEvent : NSObject <NSCoding> {

	NSString* _name;
	NSString* _mode;
	BOOL _handled;
	NSDictionary* _userInfo;

}

@property (nonatomic,readonly) NSString * name;                          //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) NSString * mode;                          //@synthesize mode=_mode - In the implementation block
@property (assign,getter=isHandled,nonatomic) BOOL handled;              //@synthesize handled=_handled - In the implementation block
@property (nonatomic,copy) NSDictionary * userInfo;                      //@synthesize userInfo=_userInfo - In the implementation block
+(id)eventWithName:(id)arg1 ;
+(id)eventWithName:(id)arg1 mode:(id)arg2 ;
-(BOOL)isHandled;
-(id)initWithName:(id)arg1 mode:(id)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)description;
-(NSString *)name;
-(void)setUserInfo:(NSDictionary *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSDictionary *)userInfo;
-(NSString *)mode;
-(id)initWithName:(id)arg1 ;
-(void)setHandled:(BOOL)arg1 ;
@end

