/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 19, 2016 at 11:57:11 AM Mountain Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libactivator.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libactivator.dylib/LASettingsViewController.h>

@class NSArray, NSMutableArray, NSString, LAListenerTableViewDataSource, ActivatorEventViewHeader, UISearchBar, UISearchController, UIView, NSDictionary, NSSet;

@interface LAEventSettingsController : LASettingsViewController {

	NSArray* _modes;
	NSMutableArray* _currentAssignments;
	NSString* _eventName;
	LAListenerTableViewDataSource* _dataSource;
	ActivatorEventViewHeader* _headerView;
	UISearchBar* _searchBar;
	UISearchController* _searchController;
	UIView* _headerWrapper;
	BOOL _modesContainsLockScreen;
	NSDictionary* _incompatibleListenerNames;
	NSString* _pendingListenerName;
	NSArray* _pendingCompatibleModes;
	BOOL _pendingIsMutuallyCompatible;
	NSSet* _configurableListenerNames;
	BOOL _viaSpecifier;

}
@end

