/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 19, 2016 at 11:57:11 AM Mountain Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libactivator.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libactivator.dylib/LASettingsViewController.h>

@class NSString, NSArray, NSMutableDictionary, UIBarButtonItem, UISearchController;

@interface LAModeSettingsController : LASettingsViewController {

	NSString* _eventMode;
	NSArray* _resolvedModes;
	NSMutableDictionary* _events;
	NSArray* _groups;
	UIBarButtonItem* _editItem;
	NSString* _searchText;
	UISearchController* _searchController;

}
@end

