//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Application.h"

@interface Application (ApplicationTesting)
+ (id)sharedTestRunner;
+ (void)commandLineTestOption:(int)arg1 arg:(const char *)arg2;
- (_Bool)didStartBookmarksTest;
- (_Bool)isRunningCanvasTest;
- (_Bool)isRunningShowBookmarksTest;
- (void)finishedBookmarksTest;
- (void)startBookmarksTest;
- (_Bool)prepareBookmarksTest;
- (void)finishedCanvasTestWithURL:(id)arg1 forTabDocument:(id)arg2;
- (void)_pollCanvasTest:(id)arg1;
- (_Bool)startCanvasTest:(id)arg1;
- (void)failedPurpleTestWithError:(id)arg1;
- (void)finishedPurpleTest:(id)arg1;
- (void)startedPurpleTest;
- (void)startTabViewRotationTest;
- (void)_prepareTabViewRotationTest;
- (void)prepareTabViewRotationTest;
- (void)startTabViewCloseTest;
- (void)_prepareTabViewCloseTest;
- (void)prepareTabViewCloseTest;
- (void)startTabViewSelectTest;
- (void)_prepareTabViewSelectTest;
- (void)prepareTabViewSelectTest;
- (void)startTabViewOpenTest;
- (void)_prepareTabViewOpenTest;
- (void)prepareTabViewOpenTest;
- (void)startTabViewBringUpTest;
- (void)_prepareTabViewBringUpTest;
- (void)prepareTabViewBringUpTest;
- (void)loadTabsForTesting:(unsigned long long)arg1 presentTabView:(_Bool)arg2;
- (void)loadBlankPageforKeyboardTests;
- (void)startKeyboardRotationTest;
- (void)startKeyboardBringupTest;
- (void)startKeyboardSplitAndMergeTest;
- (_Bool)runTest:(id)arg1 options:(id)arg2;
- (id)_numberOption:(id)arg1;
- (void)checkExtendedLaunchPageLoad:(id)arg1 forTabDocument:(id)arg2;
- (id)_extendLaunchTest;
- (_Bool)disableRestoreTabState;
- (void)startCommandLineTest;
@end

