//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Application.h"

@interface Application (ScriptingAdditions)
- (id)lastPageLoadTime;
- (id)lastPageVisualLayoutTime;
- (id)linksOnActivePage;
- (id)activeURL;
- (id)setNotifyPageLoadDidFinish:(id)arg1;
- (id)loadURLInNewWindow:(id)arg1;
- (id)loadURL:(id)arg1;
- (void)stopLoading;
- (void)scrollDocumentDown;
- (id)isAtEndOfPage;
- (id)isLoading;
@end

