//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

#import "UIApplicationDelegate.h"

@class ApplicationShortcutController, BrowserController, NSDictionary, NSString, TabDocument, UIViewController, UIWindow, WBSCloudHistory;

@interface Application : UIApplication <UIApplicationDelegate>
{
    BrowserController *_controller;
    _Bool _isReadingDefaults;
    _Bool _shouldReadDefaultsOnResume;
    _Bool _isRunningShowBookmarksTest;
    _Bool _startedBookmarksTest;
    _Bool _isRunningCanvasTest;
    _Bool _willEnterSuspendedState;
    _Bool _shouldPrepareTabDocumentForNewUserActivityWhenFinishedLaunching;
    _Bool _finishedLaunching;
    WBSCloudHistory *_cloudHistory;
    _Bool _resigningActive;
    _Bool _shouldAnimateOpeningExternalURL;
    long long _currentKeyboardModifierFlags;
    ApplicationShortcutController *_shortcutController;
    UIViewController *_obfuscatedScreenViewController;
    NSDictionary *_openURLPayload;
    TabDocument *_tabDocumentPendingUserActivityPayload;
}

@property(retain, nonatomic) WBSCloudHistory *cloudHistory; // @synthesize cloudHistory=_cloudHistory;
@property(nonatomic) __weak TabDocument *tabDocumentPendingUserActivityPayload; // @synthesize tabDocumentPendingUserActivityPayload=_tabDocumentPendingUserActivityPayload;
- (void).cxx_destruct;
- (void)_getBookmarksDataClassEnabledWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_updateCloudFeatureAvailability;
- (void)_prepareTabDocumentForNewUserActivity;
@property(retain, nonatomic) UIWindow *window;
- (void)applicationWillTerminate;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)_setHandlingURL:(_Bool)arg1 url:(id)arg2;
- (void)_appleKeyboardsChanged:(id)arg1;
- (void)_reloadSearchEngines;
- (void)userDefaultsDidChange:(id)arg1;
- (id)_openURLInNewTab:(id)arg1 withOptions:(id)arg2;
- (void)handleKeyUIEvent:(id)arg1;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;
- (void)_applicationOpenURL:(id)arg1 payload:(id)arg2;
- (void)applicationOpenURL:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)_saveNSURLCacheToDiskInBackground:(_Bool)arg1;
- (void)_saveFrequentlyVisitedSitesWhenBackgrounded;
- (void)_dismissObfuscatedScreenViewController;
- (void)_presentObfuscatedScreenViewController;
- (void)_clearSystemNavigationAction;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)clearReaderViewsExceptMultiplePageReader:(_Bool)arg1;
- (_Bool)shouldReportForegroundTabCrash;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)_applicationWillSuspend:(id)arg1;
- (void)_readDefaults;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

