//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BrowserController.h"

@interface BrowserController (BrowserControllerGestures)
- (_Bool)_isShowingFullScreenPlugInUI;
- (void)setContentOffset:(struct CGPoint)arg1;
- (struct CGPoint)contentOffset;
- (void)setZoomScale:(float)arg1;
- (float)zoomScale;
- (id)zoomAndTabTestURL;
- (void)rootViewControllerViewDidTransitionFromSize:(struct CGSize)arg1 animated:(_Bool)arg2;
- (void)rootViewControllerViewTransitionFromSize:(struct CGSize)arg1 animated:(_Bool)arg2;
- (_Bool)_canAnimateSizeTransitionOfRootViewController;
- (void)rootViewControllerViewWillTransitionToSize:(struct CGSize)arg1;
- (void)_animateRootViewControllerViewTransitionFromSize:(struct CGSize)arg1;
- (_Bool)_shouldHideBarsForSizeChange;
- (_Bool)_isShowingPopoverFromSidebar;
- (_Bool)_shouldShowSidebarForSizeChange;
- (_Bool)isRotating;
@end

