//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BrowserController.h"

#import "TabDocumentDelegate.h"

@interface BrowserController (BrowserControllerTabs) <TabDocumentDelegate>
- (void)tabDocumentDidEndNavigationGesture:(id)arg1 withNavigationToBackForwardListItem:(id)arg2;
- (void)tabDocumentWillEndNavigationGesture:(id)arg1 withNavigationToBackForwardListItem:(id)arg2;
- (void)tabDocumentDidBeginNavigationGesture:(id)arg1;
- (void)setAppBannerPinnedToTop:(_Bool)arg1 forTabDocument:(id)arg2;
- (void)removeAppBannerFromTabDocument:(id)arg1 animated:(_Bool)arg2;
- (void)tabDocumentDidCompleteCheckForAppBanner:(id)arg1;
- (void)composeEmailWithMailToURL:(id)arg1 forTabDocument:(id)arg2;
- (void)finishedTabExposeTest;
- (_Bool)isRunningTabExposeTest;
- (void)runTabExposeTest;
- (void)_runTabExposeTest;
- (_Bool)prepareTabExposeTest;
- (void)_addAuthenticationChallenge:(id)arg1 displayNow:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)loadURLInNewWindow:(id)arg1 inBackground:(_Bool)arg2 animated:(_Bool)arg3 fromExternalApplication:(_Bool)arg4;
- (id)loadURLInNewWindow:(id)arg1 inBackground:(_Bool)arg2 animated:(_Bool)arg3;
- (id)loadURLInNewWindow:(id)arg1 inBackground:(_Bool)arg2;
- (id)blankTabTitleForTabDocument:(id)arg1;
- (id)blankTabDocumentToReuse;
- (void)tabController:(id)arg1 didSwitchFromTabDocument:(id)arg2 toTabDocument:(id)arg3;
- (void)tabControllerDocumentCountDidChange:(id)arg1;
- (void)switchFromTabDocument:(id)arg1 toTabDocument:(id)arg2;
- (void)tabDocumentDidDimissPreviewedDocument:(id)arg1;
- (void)tabDocumentCommitPreviewedDocumentAsNewTab:(id)arg1 inBackground:(_Bool)arg2;
- (void)tabDocumentCommitPreviewedDocument:(id)arg1;
- (void)tabDocument:(id)arg1 didCreatePreviewDocument:(id)arg2;
- (void)_closePreviewDocumentTimerFired:(id)arg1;
- (void)_invalidatePreviewDocumentCloseTimer;
- (_Bool)tabDocumentShouldBlockPopUp:(id)arg1;
- (void)tabDocument:(id)arg1 didCreateNewTabDocument:(id)arg2;
- (void)tabDocument:(id)arg1 didDetectReaderAvailability:(_Bool)arg2;
- (void)hideAlertForTabDocument:(id)arg1;
- (void)showAlertForTabDocument:(id)arg1;
- (_Bool)tabDocumentCanShowJavaScriptAlertConfirmOrTextInput:(id)arg1;
- (_Bool)_showingAModalAlertWillHang;
- (_Bool)tabDocumentShouldHandleCertificateError:(id)arg1;
- (void)tabDocument:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)tabDocumentStoppedLoadingResource:(id)arg1;
- (void)tabDocumentFluidProgressRocketAnimationDidComplete:(id)arg1;
- (void)tabDocumentStartedLoadingResource:(id)arg1;
- (void)didStopLoadingResource;
- (void)didStartLoadingResource;
- (void)tabDocument:(id)arg1 progressChanged:(float)arg2;
- (void)tabDocumentDidUpdateBackForward:(id)arg1;
- (void)tabDocumentDidUpdateTitle:(id)arg1;
- (void)tabDocumentDidChangeLocationWithinPageForMainFrame:(id)arg1;
- (void)tabDocument:(id)arg1 didFinishLoadingWithError:(_Bool)arg2;
- (void)tabDocumentDidCancelRedirectToExternalApplication:(id)arg1;
- (_Bool)tabDocumentCanRedirectToExternalApplication:(id)arg1;
- (_Bool)tabDocumentCanDownloadFile:(id)arg1;
- (void)tabDocumentWillStartLoadFromUserClick:(id)arg1;
- (void)tabDocumentDidStartLoading:(id)arg1;
- (void)tabDocumentDidUpdateURL:(id)arg1;
- (void)tabDocumentDidUpdatePersistentState:(id)arg1;
- (void)tabDocumentDidUpdateShowingContinuous:(id)arg1;
- (_Bool)_canUpdateInterfaceWithTabDocument:(id)arg1;
@end

