//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BrowserToolbar.h"

@interface BrowserToolbar (LinkAnimations)
- (void)cancelLinkAnimations;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)animateLinkImage:(struct CGImage *)arg1 flipped:(_Bool)arg2 fromRect:(struct CGRect)arg3 toLayer:(id)arg4 orButton:(int)arg5 inView:(id)arg6 afterLinkImageDisappears:(CDUnknownBlockType)arg7 afterButtonBounces:(CDUnknownBlockType)arg8;
- (id)_pulseAnimationWithInitalTransform:(struct CATransform3D)arg1;
- (id)_bounceAnimationWithInitalTransform:(struct CATransform3D)arg1;
- (id)_toolbarItemAnimationTemplate;
- (id)_layerForButton:(int)arg1;
- (id)_fadeOutAnimation;
- (id)_scalingAnimationToFitLayerWithSize:(struct CGSize)arg1 intoItemWithSize:(struct CGSize)arg2 startingFromTransform:(struct CATransform3D)arg3;
- (id)_slightRotationAnimationStartingFromTransform:(struct CATransform3D)arg1 withRelativeAngle:(double)arg2;
- (id)_ballisticMovementAnimationFromPoint:(struct CGPoint)arg1 throughPoint:(struct CGPoint)arg2 toPoint:(struct CGPoint)arg3;
@end

