//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BrowserController.h"

#import "BookmarksBarViewDelegate.h"
#import "BookmarksNavigationControllerDelegate.h"
#import "BrowserToolbarDelegate.h"

@class NSString;

@interface BrowserController (BrowserControllerPanels) <BookmarksBarViewDelegate, BookmarksNavigationControllerDelegate, BrowserToolbarDelegate>
- (void)updatePopoverPositionAfterTransitionFromHorizontalSizeClass:(long long)arg1 toHorizontalSizeClass:(long long)arg2;
- (void)_prepareContentForMailController:(id)arg1;
- (id)_findOnPageSearchText;
- (id)bookmarksNavigationControllerCurrentContinuousReadingItem:(id)arg1;
- (void)bookmarksNavigationControllerSubscribeToCurrentWebFeed:(id)arg1;
- (id)bookmarksNavigationControllerCurrentWebFeedURL:(id)arg1;
- (void)bookmarksBarView:(id)arg1 didSelectNavigationDestination:(id)arg2;
- (long long)bookmarksNavigationControllerFavoritesGridViewLayoutType:(id)arg1;
- (void)bookmarksNavigationControllerReloadDidFail:(id)arg1;
- (void)bookmarksNavigationController:(id)arg1 activityWasSelected:(id)arg2;
- (void)bookmarksNavigationController:(id)arg1 didSelectNavigationDestination:(id)arg2;
- (void)bookmarksNavigationControllerDidTapOutsideFavorites:(id)arg1;
- (void)bookmarksNavigationControllerDidPressDoneButton:(id)arg1;
- (void)goToNavigationDestination:(id)arg1;
- (void)goToCloudTab:(id)arg1;
- (void)goToURL:(id)arg1;
- (void)_goToAutomaticReadingListItem:(id)arg1;
- (void)goToBookmark:(id)arg1;
- (void)showICSControllerForPath:(id)arg1 sourceURL:(id)arg2;
- (void)showPassBookControllerForPass:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)composeEmailWithMailToURL:(id)arg1;
- (void)animateSafariIconLinkFromPoint:(struct CGPoint)arg1 inView:(id)arg2;
- (struct CGPoint)targetPointForButtonBarLinkImageAnimationIntoLayer:(id)arg1 proposedTargetPoint:(struct CGPoint)arg2;
- (void)doSearch:(id)arg1;
- (void)addTabFromButtonBar;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)popoverController:(id)arg1 willRepositionPopoverToRect:(inout struct CGRect *)arg2 inView:(inout id *)arg3;
- (void)presentAddTabPopoverFromButtonBar;
- (void)presentForwardPopoverFromButtonBar;
- (void)presentBackPopoverFromButtonBar;
- (void)showTabsFromButtonBar;
- (void)presentBookmarksLongPressMenuFromButtonBar;
- (void)showActionPanelFromButtonBar;
- (void)toggleBookmarksFromButtonBar;
- (void)forwardFromButtonBar;
- (void)backFromButtonBar;
- (void)hideCurrentBrowserPanelAnimated:(_Bool)arg1;
- (void)closeBrowserPanel:(id)arg1;
- (_Bool)hideBrowserPanelAnimated:(_Bool)arg1;
- (_Bool)hideBrowserPanel;
- (_Bool)hideBrowserPanelType:(int)arg1;
- (_Bool)showBrowserPanelType:(int)arg1;
- (id)browserPanel;
- (void)showBookmarksPanelWithNonAnimatedTransition;
- (_Bool)_togglePanelType:(int)arg1 animated:(_Bool)arg2;
- (_Bool)_togglePanelType:(int)arg1;
- (void)_transitionToBrowserPanel:(id)arg1 animated:(_Bool)arg2;
- (void)_transitionToBrowserPanel:(id)arg1;
- (_Bool)_shouldForceInstantPanelChangeForPanelType:(int)arg1;
- (void)showLockedBookmarksDatabaseAlertInViewController:(id)arg1 forBookmarkAddition:(_Bool)arg2;
- (void)showLockedBookmarksDatabaseAlertForBookmarkAdditionAfterDelay;
- (void)_delayedShowLockedBookmarksDatabaseAlertForBookmarkAddition;
- (void)showLockedBookmarksDatabaseAlertAfterDelay;
- (void)_delayedShowLockedBookmarksDatabaseAlert;
- (id)sheetController:(id)arg1 viewControllerForAlert:(id)arg2;
- (void)sheetControllerDidHideSheet:(id)arg1;
- (void)sheetControllerDidShowSheet:(id)arg1;
- (void)didHideBrowserPanel:(id)arg1;
- (id)_panelForPanelType:(int)arg1;
- (void)willHideBrowserPanel:(id)arg1;
- (void)willShowBrowserPanel:(id)arg1;
- (void)_setNextBrowserPanel:(id)arg1;
- (void)setBrowserPanel:(id)arg1;
- (void)_setShowingCurrentPanel:(_Bool)arg1;
- (void)_setShowingCurrentPanel:(_Bool)arg1 animate:(_Bool)arg2;
- (void)sheetController:(id)arg1 performAction:(int)arg2 forAlert:(id)arg3;
- (void)_setShowingAlert:(_Bool)arg1;
- (void)_setUserInteractionEnabled:(_Bool)arg1;
- (void)_setShowingFindOnPagePanel:(_Bool)arg1;
- (_Bool)createAndAddToHomeScreenBundleForWebClip:(id)arg1;
- (void)_createInitialLaunchImageForWebClip:(id)arg1;
- (void)_setShowingActionPanel:(_Bool)arg1 animate:(_Bool)arg2;
- (void)_setShowingICSController:(_Bool)arg1;
- (void)_setShowingPrintPanel:(_Bool)arg1;
- (void)_setShowingMailComposePanel:(_Bool)arg1;
- (void)_setShowingBookmarks:(_Bool)arg1 animate:(_Bool)arg2;
- (void)_forceDismissModalViewController;
- (void)_forceDismissModalViewController:(_Bool)arg1;
- (void)dismissCurrentPopover:(_Bool)arg1;
- (void)dismissCurrentPopover;
- (_Bool)_shouldPresentViewControllerUsingAdaptivePopover:(id)arg1;
- (void)_presentModalViewController:(id)arg1 fromButtonIdentifier:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_panelSuperview;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

