//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BrowserController.h"

@interface BrowserController (BrowserControllerUI)
- (void)updateSearchEngine;
- (void)setResourcesLoading:(_Bool)arg1;
- (void)setProgress:(float)arg1;
- (void)_updateProgressIndicator;
- (void)_inputViewWillRotate:(id)arg1;
- (void)_keyboardWillHide:(id)arg1;
- (void)_keyboardWillChangeFrame:(id)arg1;
- (void)_keyboardDidShow:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (void)_updateBottomBarOffsetWithKeyboardNotification:(id)arg1;
@end

