//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BrowserController.h"

#import "ContinuousReadingViewControllerDelegate.h"

@class NSString;

@interface BrowserController (ContinuousReading) <ContinuousReadingViewControllerDelegate>
- (double)continuousReadingViewControllerNextWebViewLandingOffset:(id)arg1 includeBottomBar:(_Bool)arg2;
- (void)continuousReadingViewController:(id)arg1 didCommitToLoadItem:(id)arg2;
- (void)continuousReadingViewControllerCommitToLoadPreviousItem:(id)arg1;
- (void)continuousReadingViewControllerWillCommitToLoadNextItem:(id)arg1;
- (void)continuousReadingViewController:(id)arg1 scrollViewDidScroll:(id)arg2;
- (void)prefetchNextContinuousItemIfNeeded;
- (void)setCurrentContinuousReadingItem:(id)arg1;
- (void)_setContinuousReadingPreviewView:(id)arg1;
- (void)_updateCurrentContinuousReadingItem;
- (_Bool)_continuousScrollViewShouldScroll;
- (_Bool)_isInContinuousMode;
- (void)_updateCurrentPageBannerView;
- (void)_preparePreviousContinuousDocumentIfNeeded;
- (id)_cachedDocumentForContinuousReadingItem:(id)arg1;
- (void)_loadPreviousContinuousDocumentIfNeeded;
- (struct CGRect)_frameForCurrentPageBannerView;
- (void)_commitToTabDocumentForPreviousContinuousItem;
- (void)_commitToTabDocumentForNextContinuousItem;
- (void)loadNextContinuousDocumentIfNeeded;
- (void)_startLoadDocument:(id)arg1 continuousReadingItem:(id)arg2;
- (id)_tabDocumentForNextContinuousItem;
- (void)_prepareTabDocumentForNextContinuousItemIfNeeded;
- (void)_updateCurrentPageBannerViewBeforeContinuousTransition;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

