//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_SFToolbar.h"

@class CALayer, GestureRecognizingBarButtonItem, NSArray, NSMutableDictionary, SelectableBarButtonItem, UIBarButtonItem, UIToolbar;

@interface BrowserToolbar : _SFToolbar
{
    CALayer *_linkImageContainerLayer;
    GestureRecognizingBarButtonItem *_backItem;
    GestureRecognizingBarButtonItem *_forwardItem;
    UIBarButtonItem *_actionItem;
    SelectableBarButtonItem *_bookmarksItem;
    UIBarButtonItem *_tabExposeItem;
    GestureRecognizingBarButtonItem *_addTabItem;
    NSMutableDictionary *_defaultItemsForToolbarSize;
    NSArray *_currentItems;
    id <BrowserToolbarDelegate> _browserDelegate;
    UIToolbar *_replacementToolbar;
}

@property(retain, nonatomic) UIToolbar *replacementToolbar; // @synthesize replacementToolbar=_replacementToolbar;
@property(nonatomic) __weak id <BrowserToolbarDelegate> browserDelegate; // @synthesize browserDelegate=_browserDelegate;
- (void).cxx_destruct;
- (void)setSidebarSelected:(_Bool)arg1;
- (void)setAddTabEnabled:(_Bool)arg1;
- (void)setBookmarksLongPressEnabled:(_Bool)arg1;
- (void)setActionEnabled:(_Bool)arg1;
- (void)setForwardEnabled:(_Bool)arg1;
- (void)setBackEnabled:(_Bool)arg1;
- (void)setEnabled:(_Bool)arg1;
- (void)_bookmarksLongPressRecognized:(id)arg1;
- (void)_addTabLongPressRecognized:(id)arg1;
- (void)_backLongPressRecognized:(id)arg1;
- (void)_forwardLongPressRecognized:(id)arg1;
- (void)setItems:(id)arg1 animated:(_Bool)arg2;
- (void)dealloc;
- (id)_bookmarksItemLayer;
- (id)_tabExposeItemLayer;
- (_Bool)isMinibar;
- (void)updateTintColor;
- (void)setReplacementToolbar:(id)arg1 withAnimationDelay:(double)arg2;
- (void)_updateItemsForReplacementToolbar;
- (void)layoutSubviews;
@property(readonly, nonatomic) NSArray *defaultItems;
- (id)initWithPlacement:(long long)arg1;
- (void)_setButtonItemsTarget:(id)arg1;
- (void)_tabExposeButtonPressed;
- (struct CGRect)popoverPresentationRectForButtonIdentifier:(long long)arg1;

@end

