//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TabDocument.h"

#import "_SFSafeBrowsingControllerDelegate.h"

@class NSString;

@interface TabDocument (Phishing) <_SFSafeBrowsingControllerDelegate>
- (void)safeBrowsingControllerDidShowSecurityWarningPage:(id)arg1;
- (void)safeBrowsingControllerGoBack:(id)arg1;
- (void)safeBrowsingController:(id)arg1 didIgnoreWarningWithURL:(id)arg2;
- (void)startCheckingFraudulentWebSitesWithURL:(id)arg1;
- (void)cancelCheckForFraudulentWebsites;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

