/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 19, 2016 at 11:57:11 AM Mountain Daylight Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /usr/lib/libapplist.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewDataSource.h>

@class NSMutableArray, UITableView, NSBundle, NSArray, NSString;

@interface ALApplicationTableDataSource : NSObject <UITableViewDataSource> {

	NSMutableArray* _sectionDescriptors;
	UITableView* _tableView;
	NSBundle* _localizationBundle;
	BOOL _loadsAsynchronously;

}

@property (nonatomic,copy) NSArray * sectionDescriptors; 
@property (nonatomic,retain) UITableView * tableView;                    //@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,retain) NSBundle * localizationBundle;              //@synthesize localizationBundle=_localizationBundle - In the implementation block
@property (assign,nonatomic) BOOL loadsAsynchronously;                   //@synthesize loadsAsynchronously=_loadsAsynchronously - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)standardSectionDescriptors;
+(id)dataSource;
-(void)sectionRequestedSectionReload:(id)arg1 animated:(BOOL)arg2 ;
-(void)iconLoadedFromNotification:(id)arg1 ;
-(void)removeSectionDescriptorsAtIndexes:(id)arg1 ;
-(void)setSectionDescriptors:(NSArray *)arg1 ;
-(NSArray *)sectionDescriptors;
-(void)removeSectionDescriptorAtIndex:(long long)arg1 ;
-(void)insertSectionDescriptor:(id)arg1 atIndex:(long long)arg2 ;
-(id)displayIdentifierForIndexPath:(id)arg1 ;
-(id)cellDescriptorForIndexPath:(id)arg1 ;
-(BOOL)waitUntilDate:(id)arg1 forContentInSectionAtIndex:(long long)arg2 ;
-(BOOL)loadsAsynchronously;
-(void)setLoadsAsynchronously:(BOOL)arg1 ;
-(void)dealloc;
-(id)init;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2 ;
-(UITableView *)tableView;
-(void)setTableView:(UITableView *)arg1 ;
-(NSBundle *)localizationBundle;
-(void)setLocalizationBundle:(NSBundle *)arg1 ;
@end

