//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TUCallSoundPlayer;

@interface PHAudioInterruptionController : NSObject
{
    TUCallSoundPlayer *_player;
}

+ (id)sharedInstance;
@property(retain, nonatomic) TUCallSoundPlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)playEndedSoundForCall:(id)arg1;
- (void)playOutgoingRingSound;
- (void)stopSounds;
- (void)_ringForIncomingCall;
- (void)_captureInterruptionIfNecessaryFromCall:(id)arg1;
- (_Bool)_shouldPlayOutgoingRingingSoundForCall:(id)arg1;
- (void)_beginOrEndOutgoingRingingIfNecessaryForCall:(id)arg1;
- (void)_handleContinuityStateChange:(id)arg1;
- (void)_handleNeedsManualInCallSoundsChange:(id)arg1;
- (void)_handleHasUpdatedAudioChange:(id)arg1;
- (void)_handleManagesAudioInterruptionsChange:(id)arg1;
- (id)_activationContextForCall:(id)arg1;
- (void)_beginInterruptionForCall:(id)arg1;
- (void)_endInterruption;
- (void)_endInterruptionAfterDelay;
- (void)_cancelDelayedEndInterruption;
- (void)_handleTelephonyCallAudioFinishedNotification:(id)arg1;
- (void)_callShouldSuppressRingtoneChanged:(id)arg1;
- (void)_callInvitationSent:(id)arg1;
- (void)_callConnected:(id)arg1;
- (void)_updateAudioInterruptionsForVideoCall:(id)arg1;
- (void)_updateAudioInterruptionsForCall:(id)arg1;
- (void)_videoCallStatusChanged:(id)arg1;
- (void)_callStatusChanged:(id)arg1;
- (void)dealloc;
- (id)init;

@end

