//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface PHCallParticipantLabelDescriptor : NSObject
{
    _Bool _dynamic;
    long long _type;
    NSString *_string;
    NSArray *_strings;
}

+ (id)labelDescriptorWithArray:(id)arg1;
+ (id)labelDescriptorWithFormat:(id)arg1;
+ (id)labelDescriptorWithString:(id)arg1;
@property(nonatomic, getter=isDynamic) _Bool dynamic; // @synthesize dynamic=_dynamic;
@property(retain, nonatomic) NSArray *strings; // @synthesize strings=_strings;
@property(copy, nonatomic) NSString *string; // @synthesize string=_string;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

