//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CNContactStore;

@interface PHContactsClient : NSObject
{
    CNContactStore *_contactStore;
}

+ (id)contactsClient;
@property(retain) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
- (void).cxx_destruct;
- (id)avatarContactFromAddressBookRecord:(void *)arg1;
- (id)init;

@end

