//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVSpeechSynthesizerDelegate.h"

@class AVAudioPlayer, AVSpeechSynthesizer, NSString;

@interface PHHoldMusicAudioPlayer : NSObject <AVSpeechSynthesizerDelegate>
{
    _Bool _shouldBePlaying;
    AVAudioPlayer *_holdMusicAudioPlayer;
    AVSpeechSynthesizer *_holdMessageSpeechSynthesizer;
}

@property(nonatomic) _Bool shouldBePlaying; // @synthesize shouldBePlaying=_shouldBePlaying;
@property(retain, nonatomic) AVSpeechSynthesizer *holdMessageSpeechSynthesizer; // @synthesize holdMessageSpeechSynthesizer=_holdMessageSpeechSynthesizer;
@property(retain, nonatomic) AVAudioPlayer *holdMusicAudioPlayer; // @synthesize holdMusicAudioPlayer=_holdMusicAudioPlayer;
- (void).cxx_destruct;
- (void)speechSynthesizer:(id)arg1 didCancelSpeechUtterance:(id)arg2;
- (void)speechSynthesizer:(id)arg1 didFinishSpeechUtterance:(id)arg2;
- (void)speechSynthesizer:(id)arg1 didStartSpeechUtterance:(id)arg2;
- (_Bool)_isPlayingHoldMusic;
- (void)_stopHoldMusicAudio;
- (_Bool)_playHoldMusicAudio;
- (_Bool)_isPlayingHoldMessage;
- (void)_stopHoldMessageAudio;
- (_Bool)_playHoldMessageAudio;
@property(readonly, getter=isPlaying) _Bool playing;
- (void)stop;
- (_Bool)play;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

