//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PHInCallBackgroundStyleProtocol.h"
#import "PHInCallRootViewControllerProtocol.h"
#import "PHInCallSpringBoardEventHandlerProtocol.h"
#import "PHPhoneRemoteViewControllerDelegate.h"
#import "UIPopoverPresentationControllerDelegate.h"

@class CNContactPickerViewController, NSString, PHAudioCallViewController, PHEmergencyDialerViewController, PHPhoneRemoteViewController, PHVideoCallViewController, TUCall, UINavigationController;

@interface PHInCallRootViewController : UIViewController <PHInCallRootViewControllerProtocol, PHPhoneRemoteViewControllerDelegate, PHInCallBackgroundStyleProtocol, PHInCallSpringBoardEventHandlerProtocol, UIPopoverPresentationControllerDelegate>
{
    _Bool _dismissalWasDemandedBeforeRemoteViewControllerWasAvailable;
    long long _alertActivationReason;
    TUCall *_alertActivationCall;
    PHAudioCallViewController *_audioCallViewController;
    PHVideoCallViewController *_videoCallViewController;
    PHEmergencyDialerViewController *_emergencyDialerViewController;
    CNContactPickerViewController *_contactsViewController;
    UINavigationController *_audioCallNavigationController;
    PHPhoneRemoteViewController *_remoteViewController;
}

+ (_Bool)hasDismissalAssertions;
+ (id)dismissalAssertions;
+ (void)forceClearAllDismissalAssertions;
+ (void)releaseDismissalAssertionForReason:(id)arg1;
+ (void)obtainDismissalAssertionForReason:(id)arg1;
+ (void)setShouldLockDeviceOnNextDismiss;
+ (void)initialize;
@property(retain, nonatomic) PHPhoneRemoteViewController *remoteViewController; // @synthesize remoteViewController=_remoteViewController;
@property(retain) UINavigationController *audioCallNavigationController; // @synthesize audioCallNavigationController=_audioCallNavigationController;
@property(retain, nonatomic) CNContactPickerViewController *contactsViewController; // @synthesize contactsViewController=_contactsViewController;
@property(retain, nonatomic) PHEmergencyDialerViewController *emergencyDialerViewController; // @synthesize emergencyDialerViewController=_emergencyDialerViewController;
@property(retain, nonatomic) PHVideoCallViewController *videoCallViewController; // @synthesize videoCallViewController=_videoCallViewController;
@property(retain, nonatomic) PHAudioCallViewController *audioCallViewController; // @synthesize audioCallViewController=_audioCallViewController;
@property(retain, nonatomic) TUCall *alertActivationCall; // @synthesize alertActivationCall=_alertActivationCall;
@property long long alertActivationReason; // @synthesize alertActivationReason=_alertActivationReason;
@property _Bool dismissalWasDemandedBeforeRemoteViewControllerWasAvailable; // @synthesize dismissalWasDemandedBeforeRemoteViewControllerWasAvailable=_dismissalWasDemandedBeforeRemoteViewControllerWasAvailable;
- (void).cxx_destruct;
- (void)animateToAlert;
- (void)animateToPIP;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)resetStatusBarStyleOverrides;
- (void)setInCallStatusBarStyleOverride;
- (void)updateDesiredSpringboardBehavior;
- (void)callAudioRouteChangedEventHandler:(id)arg1;
- (void)handleDoubleHeightStatusBarTap;
- (void)handleHeadsetButtonPressed:(_Bool)arg1;
- (void)handleVolumeDownButtonPressed;
- (void)handleVolumeUpButtonPressed;
- (void)handleLockButtonPressed;
- (void)handleActivationForEndAndLock;
- (void)pullRelayingCallsIfNecessary;
- (void)releaseIdleTimerAssertionWithComment:(id)arg1;
- (void)obtainIdleTimerAssertionWithComment:(id)arg1;
- (void)setStatusBarHidden:(_Bool)arg1 withDuration:(double)arg2;
- (void)setBackgroundStyle:(long long)arg1 animatedWithDuration:(double)arg2;
- (void)viewServiceDidTerminateWithError:(id)arg1;
- (void)dismissPhoneRemoteViewControllerAnimated:(_Bool)arg1;
- (void)dismissPhoneRemoteViewController;
- (void)presentPhoneRemoteViewControllerForView:(id)arg1;
- (void)mostRecentlyDisconnectedCallDidClearNotification:(id)arg1;
- (void)emergencyCallbackModeChangedNotification:(id)arg1;
- (void)updateAlertActivationReasonForCall:(id)arg1;
- (void)updateAlertActivationReason;
- (void)dismissContactsViewControllerAnimated:(_Bool)arg1;
- (void)dismissContactsViewController;
- (void)willRotate:(id)arg1;
- (void)popoverPresentationControllerDidDismissPopover:(id)arg1;
- (void)prepareForPopoverPresentation:(id)arg1;
- (void)presentAsPopover:(id)arg1 fromView:(id)arg2;
- (void)presentContactsViewControllerForView:(id)arg1;
- (void)dismissalAssertionReleasedNotification:(id)arg1;
- (void)animateOutWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)animateInWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)prepareForDismissal;
- (void)requestInCallDismissalWithAnimation:(_Bool)arg1;
- (void)forceDismissAlert;
- (id)_remoteViewControllerProxy;
- (void)viewDidMoveToWindow:(id)arg1 shouldAppearOrDisappear:(_Bool)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)printUI;
- (void)loadView;
- (void)_transitionFromViewController:(id)arg1 toViewController:(id)arg2;
- (void)updateCallControllerForCurrentState;
- (void)callViewControllerStateChangedNotification:(id)arg1;
- (void)pipControllerDidRequestReturnToFullScreenNotification:(id)arg1;
- (void)pipStateChangedNotification:(id)arg1;
- (void)videoCallStateChangedNotification:(id)arg1;
- (void)callStateChangedNotification:(id)arg1;
- (void)_loadAudioCallViewController;
- (void)_loadVideoCallViewController;
- (void)dealloc;
- (void)_willAppearInRemoteViewController:(id)arg1;
- (void)registerForNotifications;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

