//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIRemoteAlertServiceViewController.h"

@interface PHInCallRemoteAlertShellViewController : SBUIRemoteAlertServiceViewController
{
    CDUnknownBlockType _pipFinishedTransitionBlock;
}

+ (_Bool)_isSecureForRemoteViewService;
@property(copy) CDUnknownBlockType pipFinishedTransitionBlock; // @synthesize pipFinishedTransitionBlock=_pipFinishedTransitionBlock;
- (void).cxx_destruct;
- (void)pipDidCancelNotification:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (id)_childViewController;
- (void)handleDoubleHeightStatusBarTap;
- (void)handleHeadsetButtonPressed:(_Bool)arg1;
- (void)handleVolumeDownButtonPressed;
- (void)handleVolumeUpButtonPressed;
- (void)handleLockButtonPressed;
- (_Bool)_shouldRemoveViewFromHierarchyOnDisappear;
- (void)noteActivatedForActivityContinuationWithIdentifier:(id)arg1;
- (void)noteActivatedForCustomReason:(id)arg1;
- (void)_willAppearInRemoteViewController:(id)arg1;
- (void)_stealViewControllerFromPIP;
- (void)_createRootViewController;
- (void)updateSuppressionIfNecessary;
- (void)statusChangedHandler:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

