//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet;

@interface PHInCallUtilities : NSObject
{
    NSMutableSet *_inCallStatusBarSuppressionReasons;
}

+ (id)wifiSettingsURL;
+ (id)cellularSettingsURL;
+ (id)formattedPhoneNumberFromString:(id)arg1;
+ (struct __CFPhoneNumber *)newPhoneNumberRefForDestinationID:(id)arg1 useNetworkCountryCode:(_Bool)arg2;
+ (_Bool)incomingVideoCall:(id)arg1 isUpgradeFromAudioCall:(id)arg2;
+ (id)sharedInstance;
@property(retain) NSMutableSet *inCallStatusBarSuppressionReasons; // @synthesize inCallStatusBarSuppressionReasons=_inCallStatusBarSuppressionReasons;
- (void).cxx_destruct;
- (_Bool)isIPadIdiom;
- (_Bool)faceTimeAudioIsAvailable;
- (_Bool)faceTimeAudioIsSupported;
- (_Bool)faceTimeVideoIsAvailable;
- (_Bool)faceTimeVideoIsSupported;
- (_Bool)isAuthorizedToUseAddressBook;
- (_Bool)isLockScreenMessagingAllowed;
- (_Bool)isInLostMode;
- (_Bool)isSpringBoardProximitySensorEnabled;
- (_Bool)isSpringBoardPasscodeLocked;
- (_Bool)isSpringBoardLocked;
- (void)updateInCallStatusBarSuppression;
- (void)stopSuppressingInCallStatusBarForReason:(id)arg1;
- (void)startSuppressingInCallStatusBarForReason:(id)arg1;
- (void)dealloc;
- (id)init;

@end

