//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVPlayer, AVQueuePlayer, NSDictionary, NSString, PHHoldMusicAudioPlayer, TUCall;

@interface PHRingtoneController : NSObject
{
    _Bool _interrupted;
    _Bool _lastCategoryWasTTY;
    _Bool _listeningForAVNotifications;
    _Bool _isLoggingCallAudio;
    _Bool _isObservingQueuePlayer;
    _Bool _audioMuted;
    int _pid;
    int _currentAudioCategory;
    int _currentAudioMode;
    TUCall *_callNeedingRingtone;
    NSDictionary *_currentActivationContext;
    AVQueuePlayer *_queuePlayer;
    NSString *_currentRingtoneIdentifier;
    NSDictionary *_currentVibrationPattern;
    AVPlayer *_callRecordingPlayer;
    PHHoldMusicAudioPlayer *_holdMusicAudioPlayer;
}

+ (id)sharedRingtoneController;
@property(retain, nonatomic) PHHoldMusicAudioPlayer *holdMusicAudioPlayer; // @synthesize holdMusicAudioPlayer=_holdMusicAudioPlayer;
@property(retain, nonatomic) AVPlayer *callRecordingPlayer; // @synthesize callRecordingPlayer=_callRecordingPlayer;
@property(retain, nonatomic) NSDictionary *currentVibrationPattern; // @synthesize currentVibrationPattern=_currentVibrationPattern;
@property(retain, nonatomic) NSString *currentRingtoneIdentifier; // @synthesize currentRingtoneIdentifier=_currentRingtoneIdentifier;
@property(retain, nonatomic) AVQueuePlayer *queuePlayer; // @synthesize queuePlayer=_queuePlayer;
@property(retain, nonatomic) NSDictionary *currentActivationContext; // @synthesize currentActivationContext=_currentActivationContext;
@property(retain, nonatomic) TUCall *callNeedingRingtone; // @synthesize callNeedingRingtone=_callNeedingRingtone;
@property(nonatomic) int currentAudioMode; // @synthesize currentAudioMode=_currentAudioMode;
@property(nonatomic) int currentAudioCategory; // @synthesize currentAudioCategory=_currentAudioCategory;
@property(nonatomic, getter=isAudioMuted) _Bool audioMuted; // @synthesize audioMuted=_audioMuted;
@property(nonatomic) _Bool isObservingQueuePlayer; // @synthesize isObservingQueuePlayer=_isObservingQueuePlayer;
@property(nonatomic) _Bool isLoggingCallAudio; // @synthesize isLoggingCallAudio=_isLoggingCallAudio;
@property(nonatomic) _Bool listeningForAVNotifications; // @synthesize listeningForAVNotifications=_listeningForAVNotifications;
@property(nonatomic) _Bool lastCategoryWasTTY; // @synthesize lastCategoryWasTTY=_lastCategoryWasTTY;
@property(nonatomic) _Bool interrupted; // @synthesize interrupted=_interrupted;
@property(nonatomic, setter=setPID:) int pid; // @synthesize pid=_pid;
- (void).cxx_destruct;
- (void)handleCallStatusOrShouldPlayHoldMusicChanged:(id)arg1;
- (id)vibrationPatternForAddressBookUID:(int)arg1;
- (id)ringtoneIdentifierForAddressBookUID:(int)arg1;
- (void)handleItemPlaybackDidEndNotification:(id)arg1;
- (void)handleInterruption:(id)arg1;
- (void)handleMediaServicesWereResetNotification:(id)arg1;
- (void)stopRinging;
- (void)playRingtoneWithIdentifier:(id)arg1 asset:(id)arg2 vibrationPattern:(id)arg3;
- (void)playRingtoneWithIdentifier:(id)arg1 vibrationPattern:(id)arg2;
- (void)playRingtoneForCall:(id)arg1;
- (void)endInterruption;
- (void)beginInterruptionWithAudioCategory:(int)arg1 mode:(int)arg2 activationContext:(id)arg3;
- (void)beginInterruptionWithAudioCategory:(int)arg1 activationContext:(id)arg2;
- (void)updateAudioCategory:(int)arg1 mode:(int)arg2 activationContext:(id)arg3;
- (void)updateActivationContext:(id)arg1;
- (void)updateAudioMode:(int)arg1;
- (void)updateAudioCategory:(int)arg1 activationContext:(id)arg2;
- (void)updateAudioCategory:(int)arg1;
- (void)_loadPropertiesAndStartDefaultRingtone;
- (void)_resetInterruptionState;
- (_Bool)canPlayRingtoneAsset:(id)arg1;
- (void)_loadPropertiesAndStartRingtoneWithAsset:(id)arg1 identifier:(id)arg2;
- (id)_defaultRingtoneIdentifier;
- (void)_setActivationContext:(id)arg1;
- (void)_updateAudioMode:(int)arg1;
- (void)_updateAudioCategory:(int)arg1;
- (id)_audioSessionModeNameForAudioMode:(int)arg1;
- (id)_audioSessionCategoryNameForAudioCategory:(int)arg1;
- (void)_stopCallRecordingDisclaimerPlayback;
- (void)_startCallRecordingDisclaimerPlaybackWithAsset:(id)arg1;
- (id)_callRecordingDisclaimerAsset;
- (void)_stopVibration;
- (void)_startVibrationWithPattern:(id)arg1;
- (void)_stopRingtone;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_stopObservingQueuePlayer;
- (void)_startObservingQueuePlayer;
- (void)_startRingtoneWithAsset:(id)arg1;
- (id)_ringtoneAssetWithIdentifier:(id)arg1;
- (void)_reinterruptIfNecessary;
- (_Bool)_currentCallNeedsInterruption;
- (void)_destroyQueuePlayer;
- (void)_createQueuePlayerIfNecessary;
- (void)_stopListeningForAVNotifications;
- (void)_startListeningForAVNotifications;
- (void)dealloc;
- (id)init;

@end

