//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHAbstractCallParticipantLabelView.h"

@class CNAvatarView, CNContact, NSArray, NSLayoutConstraint, NSTimer, UIButton, UILabel;

@interface PHSingleCallParticipantLabelView : PHAbstractCallParticipantLabelView
{
    CNContact *_contact;
    CNAvatarView *_avatarView;
    NSLayoutConstraint *_participantMarqueeLabelRightConstraint;
    NSLayoutConstraint *_participantMarqueeLabelAlignmentConstraint;
    NSLayoutConstraint *_participantMarqueeLabelBaselineConstraint;
    NSLayoutConstraint *_statusLabelAlignmentConstraint;
    NSLayoutConstraint *_statusLabelBaseLineConstraint;
    NSLayoutConstraint *_statusLabelRightConstraint;
    UILabel *_statusLabel;
    NSArray *_statusLabelsArray;
    NSTimer *_statusLabelTimer;
    unsigned long long _currentStatusLabelIndex;
    UIButton *_conferenceParticipantsButton;
}

@property(retain) UIButton *conferenceParticipantsButton; // @synthesize conferenceParticipantsButton=_conferenceParticipantsButton;
@property unsigned long long currentStatusLabelIndex; // @synthesize currentStatusLabelIndex=_currentStatusLabelIndex;
@property(retain) NSTimer *statusLabelTimer; // @synthesize statusLabelTimer=_statusLabelTimer;
@property(retain) NSArray *statusLabelsArray; // @synthesize statusLabelsArray=_statusLabelsArray;
@property(retain) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain) NSLayoutConstraint *statusLabelRightConstraint; // @synthesize statusLabelRightConstraint=_statusLabelRightConstraint;
@property(retain) NSLayoutConstraint *statusLabelBaseLineConstraint; // @synthesize statusLabelBaseLineConstraint=_statusLabelBaseLineConstraint;
@property(retain) NSLayoutConstraint *statusLabelAlignmentConstraint; // @synthesize statusLabelAlignmentConstraint=_statusLabelAlignmentConstraint;
@property(retain) NSLayoutConstraint *participantMarqueeLabelBaselineConstraint; // @synthesize participantMarqueeLabelBaselineConstraint=_participantMarqueeLabelBaselineConstraint;
@property(retain) NSLayoutConstraint *participantMarqueeLabelAlignmentConstraint; // @synthesize participantMarqueeLabelAlignmentConstraint=_participantMarqueeLabelAlignmentConstraint;
@property(retain) NSLayoutConstraint *participantMarqueeLabelRightConstraint; // @synthesize participantMarqueeLabelRightConstraint=_participantMarqueeLabelRightConstraint;
@property(retain, nonatomic) CNAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) CNContact *contact; // @synthesize contact=_contact;
- (void).cxx_destruct;
- (void)fadeStatusLabelToAttributedOrPlainString:(id)arg1;
- (void)animateToNextLabel;
- (void)animateToFirstLabel;
- (void)statusLabelTapped:(id)arg1;
- (void)setShouldCompressLabelsVertically:(_Bool)arg1;
- (_Bool)_statusLabelStringWillFit:(id)arg1;
- (double)_distanceFromParticipantNameBaseLineToStatus;
- (void)_setStatusLabelAlignment:(long long)arg1;
- (void)_setParticipantLabelAlignment:(long long)arg1;
- (void)infoButtonTapped:(id)arg1;
- (void)setShowsInfoButton:(_Bool)arg1;
- (void)setActivityState:(unsigned short)arg1 animated:(_Bool)arg2;
- (void)setActivityState:(unsigned short)arg1;
- (void)setHidesLabel:(_Bool)arg1;
- (void)setLabelDescriptor:(id)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

