//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIRemoteAlertServiceViewController.h"

#import "TPStarkInCallViewControllerDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSString, PHStarkHardwareControlsBroadcaster, TPStarkInCallViewController, UIView, UIViewController;

@interface PHStarkInCallViewController : SBUIRemoteAlertServiceViewController <UIGestureRecognizerDelegate, TPStarkInCallViewControllerDelegate, UINavigationControllerDelegate>
{
    _Bool _nextBackDismissesNavController;
    UIViewController *_contactsViewController;
    UIView *_flippyViewContainer;
    TPStarkInCallViewController *_mainInCallViewController;
    PHStarkHardwareControlsBroadcaster *_hardwareControlBroadcaster;
}

@property(retain) PHStarkHardwareControlsBroadcaster *hardwareControlBroadcaster; // @synthesize hardwareControlBroadcaster=_hardwareControlBroadcaster;
@property(retain) TPStarkInCallViewController *mainInCallViewController; // @synthesize mainInCallViewController=_mainInCallViewController;
@property(retain) UIView *flippyViewContainer; // @synthesize flippyViewContainer=_flippyViewContainer;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)screenDidDisconnectNotification:(id)arg1;
- (void)hardwareControlEventNotification:(id)arg1;
- (void)dismissalRequestedFromInCallViewController:(id)arg1;
- (void)presentKeypadViewControllerRequestedFromInCallViewController:(id)arg1;
- (void)cancelAddCallViewController:(id)arg1;
- (void)backPressed:(id)arg1;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)presentAddCallViewControllerRequestedFromInCallViewController:(id)arg1;
- (_Bool)activePhoneCallExists;
- (void)animateOutIfNecessary;
- (void)updateTPInCallControllerPhoneCalls;
- (void)queueUpdateToTPIncallControllerPhoneCalls;
- (void)conferencedCallsChangedNotification:(id)arg1;
- (void)callStatusChangedNotification:(id)arg1;
- (void)muteStateChangedNotification:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (id)preferredFocusedItem;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

