//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PHStarkHardwareControlsBroadcaster, PHStarkRootContainerViewController;

@interface PHStarkManager : NSObject
{
    PHStarkHardwareControlsBroadcaster *_hardwareControlsBroadcaster;
    PHStarkRootContainerViewController *_rootContainerViewController;
}

+ (_Bool)shouldLimitKeypadAccess;
@property(retain) PHStarkRootContainerViewController *rootContainerViewController; // @synthesize rootContainerViewController=_rootContainerViewController;
@property(retain) PHStarkHardwareControlsBroadcaster *hardwareControlsBroadcaster; // @synthesize hardwareControlsBroadcaster=_hardwareControlsBroadcaster;
- (void).cxx_destruct;

@end

