//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PHVideoCallViewController.h"

@interface PHVideoCallViewController (Orientation)
+ (_Bool)_shouldForwardViewWillTransitionToSize;
- (unsigned long long)_flipAnimationOptionsForOrientation:(long long)arg1;
- (void)_updateLocalVideoOrientationAnimated:(_Bool)arg1;
- (void)_adjustForOrientationAnimated:(_Bool)arg1;
- (void)_adjustForOrientationAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (long long)_preferredLocalOrientationForDeviceOrientation;
- (struct CGRect)_boundsForRemoteVideoInLocalOrientation:(long long)arg1;
- (struct CGSize)_remoteVideoAspectRatio;
- (struct CGRect)_boundsForRemoteVideoViewInLocalOrientation:(long long)arg1;
- (struct CGRect)_boundsForLocalMutedViewInLocalOrientation:(long long)arg1;
- (_Bool)_fillRemoteVideoOnScreenWithLocalOrientation:(long long)arg1 remoteAspectRatio:(struct CGSize)arg2;
- (struct CGSize)_normalizedScreenSizeForOrientation:(long long)arg1;
- (void)_adjustCallBarsForOrientation:(long long)arg1;
- (_Bool)_isValidFaceTimeOrientation:(long long)arg1;
- (double)_angleForLocalOrientation:(long long)arg1 remoteOrientation:(long long)arg2;
- (long long)_deviceOrientationForCameraOrientation:(long long)arg1;
- (long long)_cameraOrientationForDeviceOrientation:(long long)arg1;
- (void)_applyAutoRotationCorrectionForOrientation:(long long)arg1;
- (void)_resetViewLayout:(id)arg1;
- (void)_correctAutoRotationTransformForView:(id)arg1;
- (void)_applyAutoRotationCorrectionForSize:(struct CGSize)arg1 withTransform:(struct CGAffineTransform)arg2;
- (struct CGAffineTransform)_transformForInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)didChangeToDeviceOrientation:(long long)arg1;
- (void)didChangeDeviceOrientationNotification:(id)arg1;
- (void)_removeDeviceOrientationChangeObserver;
- (void)_addDeviceOrientationChangeObserver;
@end

